<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANANDASBEASTLAPTOP" name="attributes_Examples.Timeout_Attribute" tests="2" failures="0" timestamp="21 May 2024 10:05:55 GMT" time="5.026" errors="1">
  <testcase name="timeoutMethod" time="5.026" classname="attributes_Examples.Timeout_Attribute">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeoutMethod() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeoutMethod() didn't finish within the time-out 5000
	at sun.misc.Unsafe.putOrderedInt(Native Method)
	at java.util.concurrent.FutureTask.setException(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- timeoutMethod -->
  <testcase name="withoutTimeout" time="0.000" classname="attributes_Examples.Timeout_Attribute"/>
</testsuite> <!-- attributes_Examples.Timeout_Attribute -->
